# Code to build video space

Grabbed all text related with video (desctiption, transcripts, tags, etc.) and build 20,000 features using the most common words. Joined this with categorical information built by machine learning model.

In [99]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import CountVectorizer

In [85]:
video_data = pd.read_excel("processed_video_data_for_bag_of_words.xlsx")

In [86]:
video_data = video_data.set_index('video_id')

In [87]:
videofeature = pd.read_csv("video_features.csv")

In [88]:
cntVtr = CountVectorizer(ngram_range = (1,1), max_features = 20000)

In [89]:
X = cntVtr.fit_transform(list(video_data['as string']))

In [90]:
video_cnt_vtr = pd.DataFrame(X.toarray())

In [91]:
video_cnt_vtr['video_id'] = video_data.index

In [92]:
video_final = pd.merge(video_cnt_vtr, videofeature, on = "video_id")

In [94]:
video_final = video_final.set_index('video_id')

In [96]:
video_final.describe()

,0,1,2,3,4,5,6,7,8,9,...,category_Cognitive Behavioral Therapy,category_Depression,category_Managing Pain,category_Mindfulness,category_New & Expecting Mothers,category_PTSD,category_Sleep,category_Stress,category_Substance Use,category_Yoga
count,1023.000000,1023.000000,1023.000000,1023.000000,1023.000000,1023.000000,1023.000000,1023.000000,1023.000000,1023.000000,...,1023.000000,1023.000000,1023.000000,1023.000000,1023.000000,1023.000000,1023.000000,1023.000000,1023.000000,1023.000000
mean,0.034213,0.084066,0.002933,0.001955,0.002933,0.003910,0.011730,0.001955,0.001955,0.004888,...,0.109482,0.339198,0.049853,0.120235,0.019550,0.012708,0.056696,0.070381,0.078201,0.046921
std,0.268726,0.477242,0.054100,0.044194,0.054100,0.062439,0.107722,0.044194,0.062531,0.093714,...,0.312396,0.473669,0.217748,0.325395,0.138517,0.112065,0.231374,0.255914,0.268620,0.211573
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,6.000000,7.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,2.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [97]:
video_final.to_csv("video_space.csv")